"""A new audio file -> playable osu!mania 4K charts (.osz), with the timing given.

    python scripts/generate.py --audio song.mp3 --bpm 174 --offset 1234 --sr 2 3.5 5
    python scripts/generate.py --audio song.mp3 --timing timed.osu --sr 4
    python scripts/generate.py --audio song.mp3 --bpm 174 --offset 1234 --title T --artist A
    python scripts/generate.py --ckpt outputs/full-v2/best.pt --audio song.mp3 --bpm 174 \
        --offset 1234 --sr 4 --genre electronic --mapper <name or user id>
    python scripts/generate.py --ckpt outputs/full-v2/best.pt --list-styles
    python scripts/generate.py --ckpt outputs/full-v4/best.pt --audio song.mp3 --bpm 174 \
        --offset 1234 --sr 4 --stats ln=0.4,jack=0.02      # a long-note chart, few jacks

The model takes the timing as given (design doc §4.4): it places notes on the
beat grid, it does not find the beat. Give either
    --bpm and --offset    one tempo; offset = ms of the first downbeat (osu!'s red line)
    --timing X.osu        the red lines of an .osu (e.g. a map with only timing, made
                          in the osu! editor: the way mappers start anyway)
or neither: then one constant tempo is estimated from the audio (estimate_timing),
printed, and used. That is a guess, not part of the method: it fails on songs
whose tempo changes and can pick half or double time. A wrong offset shifts
every note; a wrong BPM drifts. Check with the metronome in the osu! editor, and
pass the corrected --bpm / --offset.

Audio is decoded as osu! does (src/data/audio.py), turned into log-Mel as in
preprocessing and put on the grid; the whole song is generated by continuation
at each target SR (--sr, several allowed), or chunk by chunk with --mode
independent (no context across chunks: the ablation of queue 3c). Writes to --out (default
outputs/generated/<audio stem>/): the audio, one .osu per SR, and <stem>.osz.
Open the .osz with osu! (lazer: double-click or drag onto the window; stable:
put it in Songs/ and press F5). Quiet bars are thinned by default (--loud-bias 0.1,
quiet side; 0 turns it off), which brought the loudness dynamics of 60 val songs to
the human level with the SR unchanged (EXPERIMENTS 2026-10-06).

Long notes: the model cannot tell from the audio whether a song should be a tap
chart or a long-note chart (it is the mapper's choice: EXPERIMENTS 2026-10-05). With
full-v4, --stats ln=X asks for that share; with any model --hold-bias sets how
readily long notes start (-1: about a third as often, -inf: none). Holds shorter than --min-hold cells
become taps and releases keep --release-gap empty cells before the next press
in their lane (sampler.clean_holds); by default both follow the target SR as in
human charts (sampler.HOLD_RULES: Easy 6 / 5 cells, Normal 5 / 2, Hard and up
3 / 2).

Style (a model trained with --style, src/data/style.py): --genre (a name or id from
--list-styles) and --mapper (a name or user id from the model's vocab, or "other")
choose whose charts to imitate; leave them out for no label. --style-guidance W
pushes harder towards that style (classifier-free guidance, twice the passes).

Chart stats (a model trained with --chart-stats, src/data/chartstats.py): --stats
"ln=0.4,jack=0.05,trill=0.15" asks for that long-note share (of the onsets), jack rate
(of single-note moves within a beat, the same lane again) and trill rate (of two
lane-changing moves in a row, straight back); names left out are the model's choice.
--stats sample takes all three from a random human train chart of about the same SR
(data/chart_stats.csv), printed per SR. --style-guidance W pushes towards the stats
as well (classifier-free guidance, twice the passes; EXPERIMENTS 2026-10-06). Human charts: long-note share median 0.19,
p90 0.47; jacks median 0.03, p90 0.11; trills median 0.14, p90 0.29 (240 val songs, 10-05).
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import numpy as np

from src.data import chartstats
from src.data.audio import SAMPLE_RATE, load_osu
from src.data.beat_grid import from_timing_points
from src.data.chart_parser import _split_sections
from src.data.chart_writer import write_osu
from src.data.mel import FRAMES_PER_CELL, log_mel, on_grid, song_stats
from src.data.style import GENRES, genre_index, mapper_index
from src.data.tokenizer import BAR, D, L, decode, grammar_violations, make_metas
from src.models.diffusion import load_denoiser, pick_device
from src.models.sampler import LANE_PASSES, LOUD_SIDES, ORDERS, generate_song, steps_name


def red_lines(osu: Path) -> list[tuple[float, float]]:
    """Uninherited timing points (time ms, ms per beat) of any .osu."""
    text = osu.read_text(encoding="utf-8-sig", errors="replace")
    tps = []
    for line in _split_sections(text).get("TimingPoints", []):
        f = line.split(",")
        if len(f) < 2:
            continue
        uninherited = f[6].strip() != "0" if len(f) > 6 else True
        if uninherited and float(f[1]) > 0:
            tps.append((float(f[0]), float(f[1])))
    if not tps:
        raise ValueError(f"no red line in {osu}")
    return sorted(tps)


ONSET_LAG_MS = 19.0     # flux peaks ~19 ms after chart times on real songs (EXPERIMENTS 2026-09-29)


def _fold(env: np.ndarray, step_ms: float, beat_ms: float, bins: int) -> np.ndarray:
    """Mean onset strength by position in the beat (bins per beat)."""
    phase = (np.arange(len(env)) * step_ms / beat_ms) % 1.0
    idx = np.minimum((phase * bins).astype(np.int64), bins - 1)
    return np.bincount(idx, weights=env, minlength=bins) / np.maximum(
        np.bincount(idx, minlength=bins), 1)


def estimate_timing(samples: np.ndarray, lo: float = 70.0, hi: float = 250.0
                    ) -> tuple[float, float, float]:
    """(bpm, offset ms of a strong beat, sharpness) for audio with ONE constant tempo.

    Onset strength = spectral flux of a fine log-Mel (hop 32, 1.45 ms). The tempo
    is chosen among the autocorrelation peaks within [lo, hi] BPM, weighted toward
    ~160 BPM (the dataset's typical tempo) against half-time picks, refined to
    0.002 BPM by how strongly the whole song folds onto one beat phase (a wrong
    tempo smears the fold over a long song). The offset is the fold's peak minus
    the flux lag of real songs; of the four beats of a bar the loudest is taken
    as the downbeat. sharpness = peak / mean of the fold (about 1 for no beat)."""
    hop = 32
    step = 1000.0 * hop / SAMPLE_RATE
    lm = log_mel(samples, hop=hop)
    f = np.concatenate([[0.0], np.maximum(np.diff(lm, axis=0), 0.0).sum(axis=1)])
    env = np.maximum((f - f.mean()) / (f.std() + 1e-9), 0.0)
    x = env - env.mean()
    n = 1 << int(np.ceil(np.log2(2 * len(x))))
    spec = np.fft.rfft(x, n)
    acf = np.fft.irfft(spec * np.conj(spec), n)[:len(x)]
    lags = np.arange(len(acf)) * step
    ok = (lags >= 60000.0 / hi) & (lags <= 60000.0 / lo)
    bpms = 60000.0 / np.maximum(lags, 1e-9)
    def strength(bpm: float) -> float:
        """Mean onset strength at the best phase of the beat: high only if every
        beat of the song lands on onsets (a wrong tempo drifts off them)."""
        fold = _fold(env, step, 60000.0 / bpm, 64)
        return float(np.convolve(np.r_[fold[-1], fold, fold[0]], [0.25, 0.5, 0.25], "valid").max())

    def refine(bpm: float) -> float:
        for width, res in ((0.006 * bpm, 0.02), (0.03, 0.002)):
            cands = np.arange(bpm - width, bpm + width + res / 2, res)
            bpm = float(cands[int(np.argmax([strength(b) for b in cands]))])
        return bpm

    # candidates: the strongest autocorrelation peaks in range, each refined. Double
    # time and 3/2 time put every other beat on an off-beat and score lower; half
    # time scores about the same, and the tempo prior decides
    a = np.where(ok, acf, -np.inf)
    peaks = np.flatnonzero((a[1:-1] > a[:-2]) & (a[1:-1] >= a[2:])) + 1
    cands = [refine(float(b)) for b in bpms[peaks[np.argsort(-a[peaks])][:6]]]
    def prior(bpm: float) -> float:
        return float(np.exp(-0.5 * (np.log2(bpm / 160.0) / 0.6) ** 2))

    bpm0 = max(cands, key=lambda b: strength(b) * prior(b))
    beat = 60000.0 / bpm0
    bins = max(int(beat / step), 8)
    fold = _fold(env, step, beat, bins)
    k = int(np.argmax(np.convolve(np.r_[fold[-1], fold, fold[0]], [0.25, 0.5, 0.25], "valid")))
    offset = (k + 0.5) * beat / bins - ONSET_LAG_MS
    bar = _fold(env, step, 4 * beat, 4 * bins)                  # which beat of the bar is loudest
    def around(c: int) -> float:
        return float(sum(bar[(c + d) % (4 * bins)] for d in range(-2, 3)))

    offset += beat * int(np.argmax([around(k + i * bins) for i in range(4)]))
    offset %= 4 * beat
    return bpm0, offset, float(fold.max() / (fold.mean() + 1e-9))


def song_range(timing_points, audio_ms: float) -> tuple[int, int]:
    """(cell_offset, n_cells) covering the audio from 0 ms to its end, as encode()
    with audio_ms: rows start on a bar line at or before 0 ms."""
    grid = from_timing_points(timing_points)
    lo = int(grid.cell_index(0.0, D))
    hi = int(grid.cell_index(float(audio_ms), D))
    while grid.time_from_cell(hi, D) >= audio_ms:
        hi -= 1
    cell_offset = -(-max(0, -lo) // BAR) * BAR
    return cell_offset, hi + cell_offset + 1


def model_input(samples: np.ndarray, timing_points, cell_offset: int, n_rows: int) -> np.ndarray:
    """[n_rows * 4, 80] song-standardized log-Mel on the token grid (as MelStore.chart)."""
    logmel = log_mel(samples)
    mean, std = song_stats(logmel)
    grid = from_timing_points(timing_points)
    times = grid.frame_times(-cell_offset, n_rows, frames_per_cell=FRAMES_PER_CELL)
    return (on_grid(logmel.astype(np.float16), times) - mean) / std


def safe(name: str) -> str:
    return re.sub(r'[\\/:*?"<>|]', "_", name).strip() or "song"


def list_styles(model) -> int:
    vocab = getattr(model, "style", None)
    if vocab is None:
        print("this model was trained without --style: no genres or mappers")
        return 0
    print("genres: " + ", ".join(f"{GENRES[g]} ({g})" for g in vocab["genres"]))
    print(f"mappers (>= {vocab['min_charts']} train charts each; 'other' = everyone else):")
    for m, n in zip(vocab["mappers"], vocab["mapper_charts"], strict=True):
        name = vocab["mapper_names"].get(str(m), "")
        print(f"  {m:>9d}  {n:4d} charts  {name}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--ckpt", type=Path, default=Path("outputs/full-v1/best.pt"))
    ap.add_argument("--audio", type=Path, default=None, help="the song (required)")
    ap.add_argument("--bpm", type=float, default=None)
    ap.add_argument("--offset", type=float, default=None, help="ms of the first downbeat")
    ap.add_argument("--timing", type=Path, default=None, help=".osu whose red lines to use")
    ap.add_argument("--sr", type=float, nargs="+", default=[3.0], help="target star ratings")
    ap.add_argument("--steps", type=int, default=128,   # DECISIONS 2026-09-29
                    help="forward passes per window; 0 = one cell per pass")
    ap.add_argument("--order", choices=list(ORDERS), default="random")
    ap.add_argument("--temperature", type=float, default=1.0, help="--order noisy")
    ap.add_argument("--refine", type=int, default=2,   # DECISIONS 2026-10-03
                    help="sweeps of lane refinement after sampling (sampler.refine_lanes)")
    ap.add_argument("--lane-temp", type=float, default=0.5,
                    help="--lanes forward / --refine: temperature of the lane choice "
                         "(0 = most likely lanes)")
    ap.add_argument("--lanes", choices=list(LANE_PASSES), default="forward",   # 2026-10-03
                    help="forward: choose every row's lanes again left to right with the "
                         "rhythm known (sampler.forward_lanes), before --refine")
    ap.add_argument("--spread", action="store_true",
                    help="cells opened together come from different beats (block: rows)")
    ap.add_argument("--forward-temp", type=float, default=None,
                    help="--lanes forward: its own lane temperature (default: --lane-temp)")
    ap.add_argument("--jack-bias", type=float, default=0.0,
                    help="lane passes: log-score bonus for repeating the previous onset's lanes")
    ap.add_argument("--copy-bias", type=float, default=0.0,   # 2026-10-04
                    help="after the lane passes, copy earlier bars with similar audio when the "
                         "model scores the copy within this many nats (sampler.copy_bars)")
    ap.add_argument("--no-copy", action="store_true", help="no bar copies")
    ap.add_argument("--refine-holds", action="store_true",
                    help="decide tap or long note and the release again with the whole chart "
                         "in view (sampler.refine_holds)")
    ap.add_argument("--loud-bias", type=float, default=0.1,   # 2026-10-06
                    help="fewer notes in quiet bars (sampler.loudness_bias); 0 = off")
    ap.add_argument("--onset-bias", type=float, default=0.0,
                    help="fewer notes where nothing in the music starts: EMPTY bias of up to X "
                         "on rows with weak audio onsets (sampler.onset_gate); 0 = off")
    ap.add_argument("--loud-side", choices=list(LOUD_SIDES), default="quiet",
                    help="--loud-bias: quiet bars only, or both (also more notes in loud bars)")
    ap.add_argument("--hold-share", type=float, default=None,
                    help="this share of the onsets become long notes, where the model expects "
                         "them most (0: no long notes; implies --refine-holds)")
    ap.add_argument("--empty-bias", type=float, default=0.0,
                    help="log-scale bias on EMPTY while sampling: > 0 fewer notes, < 0 more")
    ap.add_argument("--hold-bias", type=float, default=0.0,
                    help="log-scale bias on starting long notes; -1 roughly a third as many "
                         "start, -inf none (sampler.sample_window)")
    ap.add_argument("--min-hold", type=int, default=None,
                    help="long notes shorter than this many cells (1/12 beat) become taps; "
                         "0 = keep; default by SR (sampler.HOLD_RULES)")
    ap.add_argument("--release-gap", type=int, default=None,
                    help="empty cells required between a release and the next onset in its lane; "
                         "0 = keep; default by SR (sampler.HOLD_RULES)")
    ap.add_argument("--mode", choices=["continue", "independent"], default="continue")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--title", default=None, help="default: the audio file name")
    ap.add_argument("--artist", default="unknown")
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--genre", default=None, help="style: genre name or id (--list-styles)")
    ap.add_argument("--mapper", default=None,
                    help="style: mapper name or user id from the model's vocab, or other")
    ap.add_argument("--style-guidance", type=float, default=0.0,
                    help="classifier-free guidance towards --genre / --mapper (0 = none)")
    ap.add_argument("--stats", default=None,
                    help="chart stats (model trained with --chart-stats): ln=0.4,jack=0.05,"
                         "trill=0.15, or sample (a human train chart's, by SR)")
    ap.add_argument("--stats-csv", type=Path, default=Path("data/chart_stats.csv"))
    ap.add_argument("--lane-guidance", type=float, default=None,
                    help="the lane passes' own guidance weight towards the style / chart stats "
                         "(default: --style-guidance); long notes are decided before them")
    ap.add_argument("--list-styles", action="store_true",
                    help="print the genres and mappers the model knows, and stop")
    ap.add_argument("--device", default="auto")
    a = ap.parse_args(argv)
    if a.no_copy:
        a.copy_bias = None
    if a.list_styles:
        return list_styles(load_denoiser(a.ckpt, "cpu"))
    if a.audio is None:
        ap.error("--audio is required")

    if a.timing is not None:
        if a.bpm is not None or a.offset is not None:
            ap.error("give --timing or --bpm/--offset, not both")
        tps = red_lines(a.timing)
    elif a.bpm is not None and a.offset is not None:
        if a.bpm <= 0:
            ap.error("--bpm must be positive")
        tps = [(a.offset, 60000.0 / a.bpm)]
    elif a.bpm is not None or a.offset is not None:
        ap.error("give both --bpm and --offset")
    else:
        tps = None

    samples, info = load_osu(a.audio)
    if tps is None:
        bpm, offset, sharpness = estimate_timing(samples)
        tps = [(round(offset), 60000.0 / bpm)]
        print(f"timing estimated from the audio: --bpm {bpm:.3f} --offset {round(offset)} "
              f"(beat sharpness {sharpness:.2f}{'; weak, check it' if sharpness < 1.5 else ''})."
              " A guess: check it in the osu! editor and pass corrected values if off.")
    audio_ms = 1000.0 * len(samples) / SAMPLE_RATE
    cell_offset, n_cells = song_range(tps, audio_ms)
    n_rows = (-(-n_cells // L) + 1) * L                     # + overhang chunk, as sample.py
    mel = model_input(samples, tps, cell_offset, n_rows)
    stem = safe(a.audio.stem)
    title = a.title or a.audio.stem
    out = a.out or Path("outputs/generated") / stem
    out.mkdir(parents=True, exist_ok=True)
    audio_name = "audio" + a.audio.suffix.lower()
    shutil.copyfile(a.audio, out / audio_name)
    bpm = 60000.0 / tps[0][1]
    print(f"{a.audio}: {audio_ms / 1000:.1f} s, {info.get('codec')}, {bpm:.2f} BPM"
          f"{f' ({len(tps)} red lines)' if len(tps) > 1 else ''}, {n_cells:,} cells")

    model = load_denoiser(a.ckpt, pick_device(a.device))
    style = {}
    if a.genre is not None or a.mapper is not None:
        vocab = getattr(model, "style", None)
        if vocab is None:
            ap.error(f"{a.ckpt} was trained without --style: no --genre / --mapper")
        try:
            style = {"genre": None if a.genre is None else genre_index(vocab, a.genre),
                     "mapper": None if a.mapper is None else mapper_index(vocab, a.mapper)}
        except ValueError as e:
            ap.error(str(e))
    if (a.style_guidance or a.lane_guidance) and not style and a.stats is None:
        ap.error("guidance goes towards a style or chart stats: add --genre / --mapper or "
                 "--stats")
    if a.style_guidance:
        style["style_guidance"] = a.style_guidance
    spec, fixed, table = getattr(model, "chart_stats", None), None, None
    if a.stats is not None:
        if spec is None:
            ap.error(f"{a.ckpt} was trained without --chart-stats: no --stats")
        if a.stats == "sample":
            if not a.stats_csv.exists():
                ap.error(f"--stats sample: no {a.stats_csv} (scripts/build_chart_stats.py)")
            table = chartstats.read_stats(a.stats_csv)
        else:
            try:
                fixed = chartstats.parse(a.stats)
            except ValueError as e:
                ap.error(str(e))
    order = a.order if a.order != "noisy" else f"noisy{a.temperature:g}"
    if a.spread:
        order += "-spread"
    if a.lanes == "forward":
        order += "-fwd" + (f"t{a.forward_temp:g}" if a.forward_temp is not None else "")
    if a.refine:
        order += f"-ref{a.refine}t{a.lane_temp:g}"
    if a.empty_bias:
        order += f"-eb{a.empty_bias:g}"
    if a.jack_bias:
        order += f"-jb{a.jack_bias:g}"
    if a.loud_bias:
        order += f"-lb{'q' if a.loud_side == 'quiet' else ''}{a.loud_bias:g}"
    if a.onset_bias:
        order += f"-ob{a.onset_bias:g}"
    if a.refine_holds or a.hold_share is not None:
        order += "-hr" + (f"{a.hold_share:g}" if a.hold_share is not None else "")
    if a.copy_bias is not None:
        order += f"-cp{a.copy_bias:g}"
    if a.genre is not None:
        order += f"-{safe(a.genre)}"
    if a.mapper is not None:
        order += f"-by-{safe(a.mapper)}"
    if a.style_guidance:
        order += f"-sg{a.style_guidance:g}"
    if a.lane_guidance is not None:
        order += f"-lg{a.lane_guidance:g}"
    if fixed is not None:
        order += "-" + "".join(f"{chartstats.SHORT[n]}{v:g}" for n, v in fixed.items())
    elif a.stats == "sample":
        order += "-stsample"
    written = []
    for i, sr in enumerate(a.sr):
        buckets = None
        if a.stats is not None:
            wanted = fixed
            if table is not None:
                key, wanted = chartstats.sample(table, sr, np.random.default_rng([a.seed, i]))
                print(f"  s={sr:g}: style of train chart {key}: " + ", ".join(
                    f"{chartstats.SHORT[n]} {v:.3f}" for n, v in wanted.items()))
            buckets = chartstats.encode(spec, wanted)
        tokens = generate_song(model, mel, sr, tps, cell_offset, n_cells, steps=a.steps,
                               order=a.order, mode=a.mode, seed=a.seed,
                               temperature=a.temperature, refine=a.refine,
                               lane_temperature=a.lane_temp,
                               hold_bias=a.hold_bias, min_hold=a.min_hold,
                               release_gap=a.release_gap, lanes=a.lanes, spread=a.spread,
                               empty_bias=a.empty_bias, forward_temperature=a.forward_temp,
                               jack_bias=a.jack_bias, copy_bias=a.copy_bias,
                               holds=a.refine_holds, hold_share=a.hold_share, loud_bias=a.loud_bias,
                               loud_side=a.loud_side, stats=buckets, onset_bias=a.onset_bias,
                               lane_guidance=a.lane_guidance, **style)
        bad = len(grammar_violations(tokens))
        chart = decode(tokens, make_metas(tps, cell_offset, len(tokens), sr))
        chart.audio_filename = audio_name
        path = out / f"{stem} [AI s={sr:g} {a.mode}-{order}].osu"
        write_osu(path, chart, title=title, artist=a.artist,
                  version=f"AI s={sr:g} ({a.mode}/{order} T{steps_name(a.steps)})")
        written.append(path)
        nps = len(chart.notes) / max(audio_ms / 1000, 1e-9)
        lns = sum(n.end_ms is not None for n in chart.notes)
        print(f"  s={sr:g}: {len(chart.notes):,} notes ({nps:.1f}/s, long notes "
              f"{lns / max(len(chart.notes), 1):.0%}), grammar violations {bad} -> {path.name}")
    osz = out / f"{stem}.osz"
    with zipfile.ZipFile(osz, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(out / audio_name, audio_name)
        for p in written:
            z.write(p, p.name)
    print(f"{osz}: open it with osu! (lazer: double-click; stable: Songs/ + F5)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
