"""A new audio file -> playable osu!mania 4K charts (.osz), with the timing given.

    python scripts/generate.py --audio song.mp3 --bpm 174 --offset 1234 --sr 2 3.5 5
    python scripts/generate.py --audio song.mp3 --timing timed.osu --sr 4
    python scripts/generate.py --audio song.mp3 --bpm 174 --offset 1234 --title T --artist A

The model takes the timing as given (design doc §4.4): it places notes on the
beat grid, it does not find the beat. Give either
    --bpm and --offset    one tempo; offset = ms of the first downbeat (osu!'s red line)
    --timing X.osu        the red lines of an .osu (e.g. a map with only timing, made
                          in the osu! editor: the way mappers start anyway)
A wrong offset shifts every note; a wrong BPM drifts. Check the timing with the
metronome in the osu! editor if the chart feels off.

Audio is decoded as osu! does (src/data/audio.py), turned into log-Mel as in
preprocessing and put on the grid; the whole song is generated by continuation
at each target SR (--sr, several allowed). Writes to --out (default
outputs/generated/<audio stem>/): the audio, one .osu per SR, and <stem>.osz.
Open the .osz with osu! (lazer: double-click or drag onto the window; stable:
put it in Songs/ and press F5).
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import numpy as np

from src.data.audio import SAMPLE_RATE, load_osu
from src.data.beat_grid import from_timing_points
from src.data.chart_parser import _split_sections
from src.data.chart_writer import write_osu
from src.data.mel import FRAMES_PER_CELL, log_mel, on_grid, song_stats
from src.data.tokenizer import BAR, D, L, decode, grammar_violations, make_metas
from src.models.diffusion import load_denoiser, pick_device
from src.models.sampler import ORDERS, generate_song


def red_lines(osu: Path) -> list[tuple[float, float]]:
    """Uninherited timing points (time ms, ms per beat) of any .osu."""
    text = osu.read_text(encoding="utf-8-sig", errors="replace")
    tps = []
    for line in _split_sections(text).get("TimingPoints", []):
        f = line.split(",")
        if len(f) < 2:
            continue
        uninherited = f[6].strip() != "0" if len(f) > 6 else True
        if uninherited and float(f[1]) > 0:
            tps.append((float(f[0]), float(f[1])))
    if not tps:
        raise ValueError(f"no red line in {osu}")
    return sorted(tps)


def song_range(timing_points, audio_ms: float) -> tuple[int, int]:
    """(cell_offset, n_cells) covering the audio from 0 ms to its end, as encode()
    with audio_ms: rows start on a bar line at or before 0 ms."""
    grid = from_timing_points(timing_points)
    lo = int(grid.cell_index(0.0, D))
    hi = int(grid.cell_index(float(audio_ms), D))
    while grid.time_from_cell(hi, D) >= audio_ms:
        hi -= 1
    cell_offset = -(-max(0, -lo) // BAR) * BAR
    return cell_offset, hi + cell_offset + 1


def model_input(samples: np.ndarray, timing_points, cell_offset: int, n_rows: int) -> np.ndarray:
    """[n_rows * 4, 80] song-standardized log-Mel on the token grid (as MelStore.chart)."""
    logmel = log_mel(samples)
    mean, std = song_stats(logmel)
    grid = from_timing_points(timing_points)
    times = grid.frame_times(-cell_offset, n_rows, frames_per_cell=FRAMES_PER_CELL)
    return (on_grid(logmel.astype(np.float16), times) - mean) / std


def safe(name: str) -> str:
    return re.sub(r'[\\/:*?"<>|]', "_", name).strip() or "song"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--ckpt", type=Path, default=Path("outputs/full-v1/best.pt"))
    ap.add_argument("--audio", type=Path, required=True)
    ap.add_argument("--bpm", type=float, default=None)
    ap.add_argument("--offset", type=float, default=None, help="ms of the first downbeat")
    ap.add_argument("--timing", type=Path, default=None, help=".osu whose red lines to use")
    ap.add_argument("--sr", type=float, nargs="+", default=[3.0], help="target star ratings")
    ap.add_argument("--steps", type=int, default=128)   # DECISIONS 2026-09-29
    ap.add_argument("--order", choices=list(ORDERS), default="random")
    ap.add_argument("--temperature", type=float, default=1.0, help="--order noisy")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--title", default=None, help="default: the audio file name")
    ap.add_argument("--artist", default="unknown")
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--device", default="auto")
    a = ap.parse_args(argv)

    if a.timing is not None:
        if a.bpm is not None or a.offset is not None:
            ap.error("give --timing or --bpm/--offset, not both")
        tps = red_lines(a.timing)
    elif a.bpm is not None and a.offset is not None:
        if a.bpm <= 0:
            ap.error("--bpm must be positive")
        tps = [(a.offset, 60000.0 / a.bpm)]
    else:
        ap.error("the timing is an input: give --bpm and --offset, or --timing X.osu")

    samples, info = load_osu(a.audio)
    audio_ms = 1000.0 * len(samples) / SAMPLE_RATE
    cell_offset, n_cells = song_range(tps, audio_ms)
    n_rows = (-(-n_cells // L) + 1) * L                     # + overhang chunk, as sample.py
    mel = model_input(samples, tps, cell_offset, n_rows)
    stem = safe(a.audio.stem)
    title = a.title or a.audio.stem
    out = a.out or Path("outputs/generated") / stem
    out.mkdir(parents=True, exist_ok=True)
    audio_name = "audio" + a.audio.suffix.lower()
    shutil.copyfile(a.audio, out / audio_name)
    bpm = 60000.0 / tps[0][1]
    print(f"{a.audio}: {audio_ms / 1000:.1f} s, {info.get('codec')}, {bpm:.2f} BPM"
          f"{f' ({len(tps)} red lines)' if len(tps) > 1 else ''}, {n_cells:,} cells")

    model = load_denoiser(a.ckpt, pick_device(a.device))
    order = a.order if a.order != "noisy" else f"noisy{a.temperature:g}"
    written = []
    for sr in a.sr:
        tokens = generate_song(model, mel, sr, tps, cell_offset, n_cells, steps=a.steps,
                               order=a.order, mode="continue", seed=a.seed,
                               temperature=a.temperature)
        bad = len(grammar_violations(tokens))
        chart = decode(tokens, make_metas(tps, cell_offset, len(tokens), sr))
        chart.audio_filename = audio_name
        path = out / f"{stem} [AI s={sr:g}].osu"
        write_osu(path, chart, title=title, artist=a.artist,
                  version=f"AI s={sr:g} ({order} T{a.steps})")
        written.append(path)
        nps = len(chart.notes) / max(audio_ms / 1000, 1e-9)
        print(f"  s={sr:g}: {len(chart.notes):,} notes ({nps:.1f}/s), "
              f"grammar violations {bad} -> {path.name}")
    osz = out / f"{stem}.osz"
    with zipfile.ZipFile(osz, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(out / audio_name, audio_name)
        for p in written:
            z.write(p, p.name)
    print(f"{osz}: open it with osu! (lazer: double-click; stable: Songs/ + F5)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
